# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the FML version. This is currently 2.
loaderVersion="${loader_version_range}" #mandatory

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="${mod_license}"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

modId="${mod_id}" #mandatory

version="1.1.0" #mandatory

displayName="The Void Cult" #mandatory


# A file name (in the root of the mod JAR) containing a logo for display
logoFile="pack.png" #optional

# A text field displayed in the mod UI
#credits="" #optional

# The authors of the mod, displayed in the mod UI (optional)
authors="lool8421"

# The description text for the mod (multi line!) (#mandatory)
description='''
A mod that allows you to run an ender cult capable of stealing materials from other dimensions.
Obtain §dPortal Matter§r by performing "teleport" activities or killing end mobs.
Build a §5Void Altar§r with a proper beacon-like base with the blocks it asks for and craft the §3Ender Cultist Helmet§r to gain enderman trust.
Recruit endermen with §eSin-Infused Fruit§r to get them to steal resources and even mobs from other dimensions, alternatively you can eat those yourself and experience some effects.
Use §eCult Leader Staff§r to re-assign cultists up to your liking.
\n
There are 5 cultist types:\n
- §cWrath§r - Fearless but also a little sadistic, will have fun kidnapping mobs and trapping them into pearls to release whenever you want.\n
- §eGreed§r - Craving for treasures, loves their shine, will bring you all of the precious materials that can be mined underground.\n
- §6Gluttony§r - Always hungry for food but also for knowledge, will provide endless supplies of food but also aid you in enchanting.\n
- §dPride§r - Views itself above nature and to reflect it, they will bring you stolen plants to prove it.\n
- §aEnvy§r - Jealous that the end dimension is so barren, will gladly steal building blocks from other dimensions to have a better looking base.\n
- §9Sloth§r - Lazy enough to steal only already prepared loot, may bring you structure loot, or may bring you empty chests and not even care.
\n

You can customize the balance of the mod by either changing config, or creating a datapack that will overwrite the default loot tables and recipes.
No promises that it will be balanced out of the box for whatever you're making.
'''

#[[mixins]]
#config="${mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json


[[dependencies.thevoidcult]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.228,)"
    ordering="NONE"
    side="BOTH"


[[dependencies.thevoidcult]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
